### ISSUE TITLE
Negate filters

### ISSUE THREAD

**Issue by NiklasMerz** [actions/bin#25]
Is there any way to negate filters? I would like to have workflow which runs on master and one which does not run on master.

Is this possible right now? If not how can I help?

**Comment by jlelse** [comment]
I'm searching for this possibility too!

**Comment by balassit** [comment]
@NiklasMerz can you show a potential action as an example with a negation? I've thought of a couple potential ways in which negations can be done. Side note, which could become another issue, the ability to do an action multiple times (for/while loop) came to mind when I was thinking of this

**Comment by NiklasMerz** [comment]
I would like to run my deployment on any branch except master. Something like `filter !master`

**Comment by balassit** [comment]
so a full example could be:
```
action "filter-to-exclude-branch-master" {
  uses = "actions/bin/filter@master"
  args = "branch !master"
}
```
I'm wondering if that could even be done on the filter or if it needs to be done for each type of action which would be a little disappointing to have to implement everywhere. @mcolyer do you know if there is a possibility for such a feature?

**Comment by NiklasMerz** [comment]
This would be perfect for my use case. Filtering for tags etc could be good too. I already looked into the ref Script but I didnt find a good way yet.

**Comment by balassit** [comment]
@NiklasMerz this is what I came up with for the `ref` file. 
I'm new into actions (and not great with shell), but I can open a PR up if you like this solution. I'm sure there is a way to break the if statement into a case instead. I did not see any ref.bats so I was not sure on tests or anything else I would need to do. I think since the check is after the pattern match for exact on the branch name, it would not be an issue for people that name there branches starting with a `!` 

#### Command:

`./ref refs/heads/\!test`

#### Output:
`refs/heads/test is a negation of refs/heads/!test`

#### Code:

```
#!/bin/sh

set -e

pattern=$1

case "$GITHUB_REF" in
  "")
    echo "\$GITHUB_REF is not set"
    exit 1
    ;;
  $pattern)
    echo "$GITHUB_REF matches $pattern"
    exit 0
    ;;
  *)
    if [[ ${pattern##*/} == \!* ]] ;
    then
        echo "$GITHUB_REF is a negation of $pattern"
        exit 0
    fi
    echo "$GITHUB_REF does not match $pattern"
    exit 78
esac
```

**Comment by balassit** [comment]
@hfauds the branches with a starting ! would not be an issue because the logic of checking for negation looks to see if the branch starts with a ! and then that the remaining string matches. So you would put !!branch to negate !branch. While that looks odd, it works and that is basically on the people that choose to name branches with a !  

That being said, I think it is a valid argument to say something like reject. More than happy to know if other people feel the same

**Comment by NiklasMerz** [comment]
Reject sounds good, too. This could possibly be easier to understand.

**Comment by hfaulds** [comment]
@balassit I thought about this a bit more and I think problems will occur if there are two branches, `!foo` and `foo`, if I reference `!foo` is that be everything but `foo` or `!foo`.

I feel like I might be being pedantic about a corner case but I'm a bit nervous about having the query be ambiguous.

**Comment by balassit** [comment]
@hfaulds that is a good point that I had not thought of. Instead of `reject` what would you think about `exclude`? I was not sure that you could combine multiple commands together, but originally wanted to do something along those lines. If that is possible, then I think that would be a better option since it is less ambiguous

**Comment by hfaulds** [comment]
@balassit I opened a PR with what I thought tihs could look like: https://github.com/actions/bin/pull/35

**Comment by NiklasMerz** [comment]
Works perfectly for me. Thanks
